#数据源配置
spring:
  datasource:
    name: aseng-hua-market
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aseng_hua_market?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
    hikari:
      pool-name: hikariCP
      minimum-idle: 20
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: root
      connect-timeout: 5000ms
      timeout: 5000ms
      client-type: lettuce
      lettuce:
        pool:
          max-active: 10
          min-idle: 0
