server:
  port: 200209
  undertow:
    buffer-size: 1024       #\u6BCF\u5757buffer\u7684\u5927\u5C0F
    direct-buffers: true    #\u662F\u5426\u5206\u914D\u7684\u76F4\u63A5\u5185\u5B58
    threads:
      io: 16                #\u8BBE\u7F6EIO\u7EBF\u7A0B\u6570\uFF0C\u5B83\u4E3B\u8981\u6267\u884C\u975E\u963B\u585E\u7684\u4EFB\u52A1\uFF0C\u5B83\u4EEC\u4F1A\u8D1F\u8D23\u591A\u4E2A\u8FDE\u63A5\uFF0C\u9ED8\u8BA4\u8BBE\u7F6E\u6BCF\u4E2ACPU\u6838\u5FC3\u4E00\u4E2A\u7EBF\u7A0B
      worker: 256           #\u963B\u585E\u4EFB\u52A1\u7EBF\u7A0B\u6C60\uFF0C\u5F53\u6267\u884C\u7C7B\u4F3Cservlet\u8BF7\u6C42\u963B\u585E\u64CD\u4F5C\uFF0Cundertow\u4F1A\u4ECE\u8FD9\u4E2A\u7EBF\u7A0B\u6C60\u4E2D\u53D6\u5F97\u7EBF\u7A0B\uFF0C\u5B83\u7684\u503C\u8BBE\u7F6E\u53D6\u51B3\u4E8E\u7CFB\u7EDF\u7684\u8D1F\u8F7D
  servlet:
    session:
      tracking-modes: cookie

#\u9879\u76EE\u5168\u5C40\u914D\u7F6E
project:
  #\u9879\u76EE\u540D\u79F0
  name: aseng-hua-market
  #\u4E0A\u4F20\u6587\u4EF6\u7684\u9ED8\u8BA4url\u524D\u7F00
  fileUploadPath: G:\\upload\\
  #\u8BA2\u5355\u672A\u652F\u4ED8\u8D85\u65F6\u65F6\u95F4\uFF0C\u5355\u4F4D\u79D2
  orderUnpaidOverTime: 300
  #\u670D\u52A1\u5668\u5730\u5740
  serverUrl: http://localhost:200209

#\u9632\u6B62XXS\u653B\u51FB
xxs:
  #\u8FC7\u6EE4\u5F00\u5173
  enable: true
  #\u6D3E\u51FA\u94FE\u63A5\uFF08\u591A\u4E2A\u7528\u9017\u53F7\u5206\u9694\uFF09
  excludes:
  #\u5339\u914D\u94FE\u63A5
  urlPatterns: /admin/*,

#spring\u914D\u7F6E
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  session:
    timeout: 3600S
    redis:
      namespace: aseng-hua-market:session

# mybatis\u914D\u7F6E
mybatis:
  #mapper\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
mybatis-xml-reload:
  mapper-locations: classpath:mapper/*Mapper.xml

alipay:
  app-id:
  rsa-private-key:
  alipay-public_key:
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  log-path: G://aseng-hua-market//log
  signtype: RSA2